services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: elibrary-rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - elibrary

  postgres:
    image: postgres:15
    container_name: elibrary-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - elibrary

  migrate:
    image: migrate/migrate
    container_name: elibrary-migrate

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations

    command:
      [
        "-path", "/migrations",
        "-database",
        "${DB_URL}",
        "up"
      ]

    networks:
      - elibrary

  backend:
    build: .
    container_name: elibrary-backend
    restart: unless-stopped

    depends_on:
      migrate:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started

    environment:
      DB_URL: ${DB_URL}
      HTTP_ADDR: ${HTTP_ADDR:-:8080}
      JWT_SECRET: ${JWT_SECRET}
      IMAGES_PATH: ${IMAGES_PATH:-/app/data/images}
      IMAGES_URL: ${IMAGES_URL:-/static/images}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:3000}
      RABBIT_URL: ${RABBIT_URL}
      RABBIT_QUEUE: ${RABBIT_QUEUE:-print_queue}

    ports:
      - "8080:8080"

    expose:
      - "8080"

    volumes:
      - /home/root/elibrary-data/images:/app/data/images

    networks:
      - elibrary
      - web

  frontend:
    build: ./client
    container_name: elibrary-frontend
    restart: unless-stopped

    expose:
      - "80"

    networks:
      - web

volumes:
  pgdata:

networks:
  elibrary:
  web:
    external: true
